### ISSUE TITLE
US08 - Importação automática de processos em CSV

### ISSUE THREAD

**Issue by Denniel-sudo** [fga-eps-mds/2023-1-CAPJu-Doc#205]
## Descrição da História
Eu, como servidor, diretor ou administrador gostaria de importar automaticamente os processos através de um arquivo csv para poder realizar a importação de forma mais prática.

## Tasks
- [ ] Definir formato template de csv a ser aceito
- [ ] Criar protótipo
- [ ] Definir estrutura a ser enviada ao back-end
- [ ] Construção front-end
- [ ] Construção back-end

## Critérios de Aceitação
Seção para os critérios que definem acerca da aceitação da tarefa. 
- [ ] Aceite de somente arquivos csv
- [ ] Aceite da formatação padrão do csv
- [ ] Visualizar processos importados na página sem perda de informação
