### ISSUE TITLE
Lista de Entrega da Release R_1 (major)

### ISSUE THREAD

**Issue by RodrigoTCLima** [fga-eps-mds/2023-1-CAPJu-Doc#33]
# Documentação da R1

## Descrição.
Criação/atualização de documentos referentes ao Projeto.
  
## Critérios de aceitação
- [x] #109 
- [x] #35
- [x] #60
- [x] #61
- [x] #127
- [x] #49
- [x] #50
- [x] #37
- [x] Backlog inicial do Produto / Incremento Produto(inclui o mapeamento e correções dos defeitos); 
- [x] #40;
- [x] #43;
- [x] #52; 
- [x] Configuração/Revisão do repositório de acordo com os padrões de comunidade de software livre (ex: como contribuir, licença, código de conduta,...); 
- [x] #22 
- [x] #53 
- [ ] Plano Qualidade; 
- [x] Wiki atualizada; 
- [x] #152
- [x] #34
- [ ] Testes em nível unitário, integração e sistema; 
- [ ] #2
- [x] #145
- [x] #62
- [x] #106
